<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUe5g4QU\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUe5g4QU/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUe5g4QU.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUe5g4QU\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUe5g4QU\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ue5g4QU',
    'container.build_id' => 'db1b61c5',
    'container.build_time' => 1592267513,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUe5g4QU');
