<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'books_index' => [[], ['_controller' => 'App\\Controller\\api\\BookController::list'], [], [['text', '/api/books']], [], []],
    'books_show' => [['id'], ['_controller' => 'App\\Controller\\api\\BookController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/api/books']], [], []],
    'books_delete' => [['id'], ['_controller' => 'App\\Controller\\api\\BookController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/api/books']], [], []],
    'books_update' => [['id'], ['_controller' => 'App\\Controller\\api\\BookController::update'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/api/books']], [], []],
    'books_create' => [[], ['_controller' => 'App\\Controller\\api\\BookController::create'], [], [['text', '/api/books/']], [], []],
];
